interface IStates {
    name: string;
    isLandlocked: boolean;
    isBorderedByCanada: boolean;
    isEastCoast: boolean;
    isTheLargest: boolean;
    isTwoPartName: boolean;
    is5000High: boolean;
    is10Millions: boolean;
    isCapitol: boolean;
    isBigTen: boolean;
    isIslands: boolean;
    isTennesseeBordering: boolean;
    isOnGreatLakes: boolean;
    [key: string]: string|boolean;
}

const states: IStates[]= [
    {name: "Alabama", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: true, isOnGreatLakes: false,},
    {name: "Alaska", isLandlocked: false, isBorderedByCanada: true, isEastCoast: false, isTheLargest: true,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: true, isTennesseeBordering: false,isOnGreatLakes: false,},
    {name: "Arizona", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: false, isTennesseeBordering: false,isOnGreatLakes: false,},
    {name: "Arkansas", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: false, isTennesseeBordering: true,isOnGreatLakes: false,},
    {name: "California", isLandlocked: false, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: true, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false,isOnGreatLakes: false,},
    {name: "Colorado", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: false, isTennesseeBordering: false,isOnGreatLakes: false,},
    {name: "Connecticut", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false,isOnGreatLakes: false,},
    {name: "Delaware", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false,isOnGreatLakes: false,},
    {name: "Florida", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: true, isCapitol: false, isBigTen: false,
        isIslands: true, isTennesseeBordering: false,isOnGreatLakes: false,},
    {name: "Georgia", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: true, isCapitol: true, isBigTen: false,
        isIslands: false, isTennesseeBordering: true,isOnGreatLakes: false,},
    {name: "Hawaii", isLandlocked: false, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: true, isTennesseeBordering: false,isOnGreatLakes: false,},
    {name: "Idaho", isLandlocked: true, isBorderedByCanada: true, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: false, isTennesseeBordering: false,isOnGreatLakes: false,},
    {name: "Illinois", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: true, isCapitol: false, isBigTen: true,
        isIslands: false, isTennesseeBordering: false,isOnGreatLakes: true,},
    {name: "Indiana", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: true, isBigTen: true,
        isIslands: false, isTennesseeBordering: false,isOnGreatLakes: true,},
    {name: "Iowa", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: true, isBigTen: true,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Kansas", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Kentucky", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: true, isOnGreatLakes: false,},
    {name: "Louisiana", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Maine", isLandlocked: false, isBorderedByCanada: true, isEastCoast: true, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Maryland", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: true,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Massachusetts", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: true, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Michigan", isLandlocked: true, isBorderedByCanada: true, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: true, isCapitol: false, isBigTen: true,
        isIslands: true, isTennesseeBordering: false, isOnGreatLakes: true,},
    {name: "Minnesota", isLandlocked: true, isBorderedByCanada: true, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: true,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: true,},
    {name: "Mississippi", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: false, isTennesseeBordering: true, isOnGreatLakes: false,},
    {name: "Missouri", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: true, isOnGreatLakes: false,},
    {name: "Montana", isLandlocked: true, isBorderedByCanada: true, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Nebraska", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: false, isBigTen: true,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Nevada", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "New Hampshire", isLandlocked: false, isBorderedByCanada: true, isEastCoast: true, isTheLargest: false,
        isTwoPartName: true, is5000High: true, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "New Jersey", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: true, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: true,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "New Mexico", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: true, is5000High: true, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "New York", isLandlocked: false, isBorderedByCanada: true, isEastCoast: true, isTheLargest: false,
        isTwoPartName: true, is5000High: true, is10Millions: true, isCapitol: false, isBigTen: false,
        isIslands: true, isTennesseeBordering: false, isOnGreatLakes: true,},
    {name: "North Carolina", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: true, is5000High: true, is10Millions: true, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: true, isOnGreatLakes: false,},
    {name: "North Dakota", isLandlocked: true, isBorderedByCanada: true, isEastCoast: false, isTheLargest: false,
        isTwoPartName: true, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Ohio", isLandlocked: true, isBorderedByCanada: true, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: true, isCapitol: true, isBigTen: true,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: true,},
    {name: "Oklahoma", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Oregon", isLandlocked: false, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Pennsylvania", isLandlocked: true, isBorderedByCanada: true, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: true, isCapitol: false, isBigTen: true,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: true,},
    {name: "Rhode Island", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: true, is5000High: false, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: true, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "South Carolina", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: true, is5000High: false, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "South Dakota", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: true, is5000High: true, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Tennessee", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Texas", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: true, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Utah", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Vermont", isLandlocked: true, isBorderedByCanada: true, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: true, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Virginia", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: false, isTennesseeBordering: true, isOnGreatLakes: false,},
    {name: "Washington", isLandlocked: false, isBorderedByCanada: true, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: false, isBigTen: false,
        isIslands: true, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "West Virginia", isLandlocked: false, isBorderedByCanada: false, isEastCoast: true, isTheLargest: false,
        isTwoPartName: true, is5000High: false, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
    {name: "Wisconsin", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: false, is10Millions: false, isCapitol: false, isBigTen: true,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: true,},
    {name: "Wyoming", isLandlocked: true, isBorderedByCanada: false, isEastCoast: false, isTheLargest: false,
        isTwoPartName: false, is5000High: true, is10Millions: false, isCapitol: true, isBigTen: false,
        isIslands: false, isTennesseeBordering: false, isOnGreatLakes: false,},
];


export default states;
